name: UltimateArena
main: com.orange451.UltimateArena.UltimateArena
version: 2.0
authors: [orange451, dmulloy2]
softdepend: [PVPGunPlus]
description: The Ultimate in Minecraft death sports and spleef
commands: 
  ua:
    description: Ultimate Arena base command
    usage:
  tt:
    description: Ultimate Arena test API
    usage: