name: UltimateArena
main: com.orange451.UltimateArena.UltimateArena
version: 1.0
website: http://orangegaming.webatu.com/
author: orange451
commands: 
  ua:
    description:
    usage:
  tt:
    description:
    usage: