######################################################
#+--------------------------------------------------+#
#|                                                  |#
#|                   UltimateArena                  |#
#|               Global Configuration               |#
#|                                                  |#
#+--------------------------------------------------+#
######################################################

# By dmulloy2
#
# If you get configuration errors, check here:
# https://github.com/MineSworn/UltimateArena/blob/master/src/main/resources/config.yml
#
# Configuration Explanation found here:
# http://dev.bukkit.org/bukkit-plugins/ultimatearena/pages/configuration/
#
# This configuration follows standard YAML procedure, found here:
# http://yaml.org/

# Whether or not cash rewards are given upon completion
# Input - boolean
moneyrewards: true

# Time a player must stand still before joining the arena
# Enabled - boolean
# Wait - integer (in seconds)
joinTimer:
  enabled: true
  wait: 3
  
# Whether or not the plugin will save inventories
# Input - boolean
saveInventories: true

# Extra output to console
# Default - false; Input - boolean
debug: false

# Timer XP bar
# Default - false; Input - boolean
timerXPBar: true

# Class Selection GUI
# title - Inventory title
# automatic - Open automatically in lobby
classSelector:
  title: "         &l&nSelect a class!&r"
  automatic: true

# Restrict commands
# Whether or not to restrict commands
# See: whitelistedCommands
# Default - true; Input - boolean
restrictCommands: true

# Whitelisted Commands
# Commands players can use in arenas
# # See: restrictCommands
# Input - List<String>
whitelistedCommands:
- "/f c"
- "/msg"
- "/r"
- "/who"
- "/god off"
- "/list"
- "/t"
- "/tell"