name: UltimateArena
main: net.dmulloy2.ultimatearena.UltimateArena
version: "${project.version}.${BUILD_NUMBER}"
author: dmulloy2
softdepend: [WorldEdit, Vault, Essentials, Multiverse-Core]
description: The Ultimate in Minecraft death sports and spleef!
load: postworld
commands:
  ua:
    description: Ultimate Arena base command
    usage: /<command> <args>
    aliases: [ultimatearena]

permissions:
  ultimatearena.admin:
    description: Allows access to all UltimateArena features
    default: false
    children:
      ultimatearena.builder: true
      ultimatearena.forcestop: true
      ultimatearena.reload: true
      ultimatearena.disable: true
      ultimatearena.enable: true
      ultimatearena.kick: true
      ultimatearena.start: true
      ultimatearena.pause: true
      ultimatearena.bypass: true
  ultimatearena.builder:
    description: Allows access to features meant for builders
    default: false
    children:
      ultimatearena.create: true
      ultimatearena.setpoint: true
      ultimatearena.setdone: true
      ultimatearena.delete: true
      ultimatearena.stop: true
      ultimatearena.build: true
  ultimatearena.class:
    description: Allows the switching of classes ingame
    default: true
  ultimatearena.classlist:
    description: Allows the listing of classes
    default: true
  ultimatearena.create:
    description: Allows the creation of arenas
    default: false
  ultimatearena.delete:
    description: Allows the deletion of arenas
    default: false
  ultimatearena.disable:
    description: Allows the disabling of arenas
    default: false
  ultimatearena.dislike:
    description: Allows the disliking of arenas
    default: true
  ultimatearena.enable:
    description: Allows the enabling of arenas
    default: false
  ultimatearena.forcestop:
    description: Allows the force stopping of arenas
    default: false
  ultimatearena.info:
    description: Allows the viewing of arena info
    default: true
  ultimatearena.join:
    description: Allows the joining of arenas
    default: true
  ultimatearena.join.force:
    description: Allows the forceful joining of arenas
    default: false
  ultimatearena.kick:
    description: Allows the kicking of players from arenas
    default: false
  ultimatearena.like:
    description: Allows the liking of arenas
    default: true
  ultimatearena.list:
    description: Allows the listing of available arenas
    default: true
  ultimatearena.pause:
    description: Allows the pausing of arena start timers
    default: false
  ultimatearena.reload:
    description: Allows the reloading of the UltimateArena plugin
    default: false
  ultimatearena.setdone:
    description: Allows the usage of /ua done
    default: false
  ultimatearena.setpoint:
    description: Allows the usage of /ua setpoint
    default: false
  ultimatearena.spectate:
    description: Allows the usage of /ua spectate
    default: true
  ultimatearena.start:
    description: Allows the force starting of arenas
    default: false
  ultimatearena.stats:
    description: Allows the viewing of arena stats
    default: true
  ultimatearena.stop:
    description: Allows the usage of /ua stop
    default: false
  ultimatearena.version:
    description: Allows usage of /ua version
    default: true
  ultimatearena.build:
    description: Allows the breaking and placing of blocks in arenas
    default: false
  ultimatearena.bypass:
    description: Allows a player to bypass whitelisted commands
    default: false