# Ultimate Arena Global Configuration
# By dmulloy2

# Whether or not cash rewards are given upon completion
# Input - boolean
moneyrewards: true

# Time a player must stand still before joining the arena
# Enabled - boolean
# Wait - integer (in seconds)
joinTimer:
  enabled: true
  wait: 3
  
# Whether or not the plugin will save inventories
# Input - boolean
saveInventories: false

# Whether or not SwornGuns ammo is unlimited
# Default - true; Input - boolean
unlimitedAmmo: true

# Extra output to console
# Default - false; Input - boolean
debug: false

# Timer XP bar
# Default - false; Input - boolean
timerXPBar: false