name: UltimateArena
main: com.orange451.UltimateArena.UltimateArena
version: 2.2
authors: [dmulloy2, orange451]
softdepend: [PVPGunPlus, Vault]
description: The Ultimate in Minecraft death sports and spleef!
commands: 
  ua:
    description: Ultimate Arena base command
    usage:
  tt:
    description: Ultimate Arena test API
    usage:
permissions:
  ultimatearena.player:
    default: true
  ultimatearena.builder:
    default: op
  ultimatearena.admin:
    default: op