# Main Configuration for the Bomb Arena Type
# http://dev.bukkit.org/bukkit-plugins/ultimatearena/pages/configuration/

gameTime: 900
lobbyTime: 70
maxDeaths: 990
allowTeamKilling: false
countMobKills: false
rewardBasedOnXp: true
cashReward: 100
rewards:
- 266,3
- 46,1