# Main Configuration for the Conquest Arena Type
# http://dev.bukkit.org/bukkit-plugins/ultimatearena/pages/configuration/

gameTime: 1200
lobbyTime: 180
maxDeaths: 900
allowTeamKilling: false
countMobKills: false
rewardBasedOnXp: true
cashReward: 100
rewards:
- 266,3
- 46,1