# Main Configuration for the FFA Arena Type
# http://dev.bukkit.org/bukkit-plugins/ultimatearena/pages/configuration/

gameTime: 600
lobbyTime: 70
maxDeaths: 3
allowTeamKilling: true
rewardBasedOnXp: true
countMobKills: false
cashReward: 100
rewards:
- 266,3
- 46,1